<?php
// auto-generated by sfViewConfigHandler
// date: 2010/07/05 10:20:12
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('screen', '', array (  'media' => 'screen',));
  $response->addStylesheet('print', '', array (  'media' => 'print',));
  $response->addStylesheet('clickmenu', '', array ());
  $response->addStylesheet('smoothness/jquery-ui-1.8.custom.css', '', array ());
  $response->addStylesheet('master', '', array ());
  $response->addJavascript('jquery-1.4.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.custom.min.js', '', array ());
  $response->addJavascript('jquery.clickmenu.js', '', array ());


